"use client";
import {useEffect,useRef,useState} from "react";
import type {Project} from "@/data/projects";
import profile from "../../../content/profile.json";
import {ProjectArt} from "../ProjectArt";
import {ResultsExplorer} from "../ResultsExplorer";
import {DirectionScene} from "./DirectionScene";
import {type Direction} from "./config";
import {AtelierSculpture} from "./AtelierSculpture";
import {AtelierNavigation} from "./AtelierNavigation";
import {useAtelierJournalMotion} from "./useAtelierJournalMotion";
import {useDirectionMotion} from "./useDirectionMotion";
import s from "./directions.module.css";
const portrait="/images/sudharsan-polished.png";
const studio="/images/studio-portrait-v1.png";
const background=[
 {number:"01",label:"Operations",date:"2021 — 2025",title:"People & processes",text:"Supervisor at Sai Ram Industries, India. Workforce coordination, attendance records and everyday operational responsibilities."},
 {number:"02",label:"Education",date:"Expected October 2027",title:"Computer science",text:"MSc Computer Science and Technology at Ulster University through QA Higher Education."},
 {number:"03",label:"Direction",date:"Building towards",title:"A career in data",text:"UK Data Analyst opportunities, with a parallel interest in junior analytics engineering. Developing SQL, Power BI and reproducible workflows."},
];
const Arrow=()=> <span aria-hidden="true">↗</span>;
function Type({children}:{children:React.ReactNode}){return <span className={s.line}><span data-title-line>{children}</span></span>;}
function Art({project}:{project:Project}){return <div className={s.projectArt}><ProjectArt kind={project.visual}/><span className={s.artNote}>Concept illustration</span></div>;}

export function DirectionExperience({direction:d,projects}:{direction:Direction;projects:Project[]}){
 const root=useRef<HTMLDivElement>(null),progress=useRef(0),modal=useRef<HTMLDialogElement>(null),quick=useRef<HTMLDialogElement>(null),menu=useRef<HTMLDialogElement>(null);
 const [paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[selected,setSelected]=useState(0),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[tab,setTab]=useState("contribution"),[opened,setOpened]=useState<Project|null>(null);
 useEffect(()=>{const m=matchMedia("(prefers-reduced-motion: reduce)");const change=()=>setReduced(m.matches);change();m.addEventListener("change",change);return()=>m.removeEventListener("change",change);},[]);
 useDirectionMotion(root,progress,d.slug,paused,reduced);
 useEffect(()=>{if(!opened)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=old;};},[opened]);
 const categories=["All",...new Set(projects.map(p=>p.category))];
 const filtered=projects.filter(p=>(filter==="All"||p.category===filter)&&[p.title,p.summary,p.role,...p.tools].join(" ").toLowerCase().includes(query.toLowerCase().trim()));
 useAtelierJournalMotion(root,d.slug==="atelier",paused,reduced,filtered.map(p=>p.slug).join("|"));
 const active=filtered[Math.min(selected,Math.max(0,filtered.length-1))];
 const open=(p:Project)=>{setOpened(p);modal.current?.showModal();};
 const action=(p:Project)=> <button type="button" className={s.caseLink} onClick={()=>open(p)}>Explore case study <Arrow/></button>;
 const select=(index:number)=>{setSelected(index);setTab("contribution");};
 const heroPhoto=(image=portrait)=> <div data-hero-photo className={s.heroPhoto}><img src={image} alt="Polished portrait of Sudharsan Sankaran wearing sunglasses." width={image===portrait?1024:1672} height={image===portrait?1536:941} fetchPriority="high"/></div>;
 const labels=<div className={s.heroFoot}><span>MSc Computer Science & Technology</span><a href="#about">Scroll to discover <span aria-hidden="true">↓</span></a><span>Ulster University / QA Higher Education</span></div>;
 return <div className={s.root} data-direction={d.slug} data-paused={paused||reduced} ref={root}>
  <a className={s.skip} href="#work">Skip to work</a>
  <header className={s.header}>
   <a className={s.brand} href="#home" aria-label="Sudharsan Sankaran home">{d.slug==="terminal"?"SS_":"SS"}<span aria-hidden="true">{d.slug==="orbit"?"✳":d.slug==="prism"?"✶":"."}</span></a>
   <span className={s.identity}>{d.slug==="atelier"?"Sudharsan Sankaran / Personal journal":"Sudharsan Sankaran"}</span>
   <nav aria-label="Main navigation"><a href="#about">About</a><a href="#work">Work</a><a href="#contact">Contact</a></nav>
   <button type="button" className={s.quickButton} onClick={()=>quick.current?.showModal()}>Recruiter view <Arrow/></button>
   <button type="button" className={s.menuButton} onClick={()=>menu.current?.showModal()} aria-label="Open navigation">Menu <span aria-hidden="true">+</span></button>
  </header>
  <main>
   <div className={s.heroTrack} data-hero-track id="home">
    <section className={s.hero} aria-labelledby="direction-name">
     <div className={s.scene}><div className={s.sceneFallback}/><DirectionScene mode={d.slug} paused={paused||reduced||!!opened} progress={progress}/></div>
     {d.slug==="orbit"&&<><p className={s.heroEyebrow}>A personal universe / Data & technology</p>{heroPhoto()}<div className={s.heroType} data-hero-type><h1 id="direction-name"><Type>SUDHARSAN</Type><Type><em>SANKARAN</em></Type></h1></div><p className={s.heroDescription}>An operations perspective.<br/>An expanding world of data.</p><a className={s.roundCta} href="#work">Enter<br/>the work <Arrow/></a><span className={s.orbitCoordinate}>01° / Always exploring</span></>}
     {d.slug==="form"&&<><div className={s.heroType} data-hero-type><p className={s.heroEyebrow}>Computer science student. Human perspective.</p><h1 id="direction-name"><Type>SUDHAR</Type><Type>SAN<span className={s.accent}>✳</span></Type></h1><p className={s.formFootnote}>SANKARAN / DATA & TECHNOLOGY</p></div>{heroPhoto(studio)}<div className={s.formCaption}><span>FROM OPERATIONS<br/>TOWARDS DATA.</span><a href="#work">VIEW WORK <Arrow/></a></div></>}
     {d.slug==="atelier"&&<><div className={s.heroType} data-hero-type><p className={s.heroEyebrow}>A personal journal / Data & technology</p><h1 id="direction-name"><Type>Sudharsan</Type><Type><em>Sankaran.</em></Type></h1><p className={s.heroDescription}>From operations.<br/>Towards a career in data.</p><a className={s.textCta} href="#work">Explore the journal <Arrow/></a></div>{heroPhoto(studio)}<div className={s.cinemaShade} data-cinema-shade/><div className={s.cinemaCopy} data-cinema-copy><span className={s.micro}>A different perspective</span><h2>People first.<br/><em>Patterns next.</em></h2><p>Operations experience. Computer science.<br/>A growing practice in data.</p><a href="#about">Meet the person behind the work <Arrow/></a></div><span className={s.edition}>Personal portfolio<br/>Notes on data & technology</span><div className={s.cinemaProgress} aria-hidden="true"><span>Perspective</span><i><b data-cinema-progress/></i><span>01 — 03</span></div></>}
     {d.slug==="prism"&&<><span className={s.heroEyebrow}>A different angle on data.</span>{heroPhoto()}<div className={s.heroType} data-hero-type><h1 id="direction-name"><Type>HELLO,</Type><Type>I’M <em>SUDHAR</em></Type><Type><em>SAN.</em></Type></h1></div><a className={s.prismCta} href="#work">TAKE A LOOK <Arrow/></a><p className={s.heroDescription}>Operations experience.<br/>Computer science. Curiosity.</p></>}
     {d.slug==="terminal"&&<><div className={s.heroType} data-hero-type><p className={s.heroEyebrow}><i/> Personal workspace / Data & technology</p><h1 id="direction-name"><Type>Sudharsan</Type><Type>Sankaran<span className={s.cursor}>_</span></Type></h1><p className={s.heroDescription}>I’m exploring how data becomes useful.<br/>Start with the work. Inspect the thinking.</p><a className={s.terminalCta} href="#work"><span aria-hidden="true">&gt;_</span> Open project explorer <Arrow/></a></div>{heroPhoto(studio)}<div className={s.terminalMeta}><span>FOCUS / UK DATA ANALYST</span><span>STUDY / MSc COMPUTER SCIENCE</span><span>STATUS / LEARNING & BUILDING</span></div></>}
     {d.slug==="horizon"&&<><div className={s.heroType} data-hero-type><p className={s.heroEyebrow}>The next perspective</p><h1 id="direction-name"><Type>SUDHARSAN</Type><Type><em>SANKARAN</em></Type></h1></div>{heroPhoto()}<p className={s.heroDescription}>An operations background.<br/>A new direction in data.</p><a className={s.horizonCta} href="#work">Explore the chapters <span aria-hidden="true">↓</span></a></>}
     <div className={s.heroEnd} data-hero-end><span>Past experience. New questions.</span><a href="#about">Discover my perspective <Arrow/></a></div>
     {labels}
    </section>
   </div>

   <section className={s.about} id="about" aria-labelledby="about-heading">
    <div className={s.sectionLabel}><span>01 / The person</span><span>{d.slug==="terminal"?"profile.read()":"Context before conclusions"}</span></div>
    <div className={s.aboutLead} data-reveal><h2 id="about-heading">{d.slug==="form"?<>PEOPLE.<br/>PROCESS.<br/><em>PERSPECTIVE.</em></>:d.slug==="prism"?<>A little<br/><em>unexpected.</em></>:d.slug==="terminal"?<>The person<br/>behind the <em>process.</em></>:<>Curiosity,<br/><em>with context.</em></>}</h2><div><p>{profile.intro}</p><p>My route into computing brings together mechanical engineering, industrial team supervision and a growing interest in data.</p></div></div>
    <div className={s.background}>{background.map(item=><article key={item.number} data-reveal><span className={s.backgroundNumber}>{d.slug==="atelier"?item.number=== "01"?"Then.":item.number==="02"?"Now.":"Next.":item.number}</span><div><span className={s.micro}>{item.date}</span><h3>{item.title}</h3><p>{item.text}</p><span className={s.backgroundLabel}>{item.label}</span></div></article>)}</div>
    <div className={s.practice} data-reveal><span className={s.micro}>Current practice</span><p>R modelling <span>↗</span> Python coursework <span>↗</span> Deployment support</p><span className={s.practiceNote}>Developing next: SQL · Power BI · Reproducible workflows</span></div>
   </section>

   <section className={s.work} id="work" aria-labelledby="work-heading">
    <div className={s.sectionLabel}><span>02 / Selected work</span><span>{projects.length.toString().padStart(2,"0")} projects / An expanding collection</span></div>
    <div className={s.workLead} data-reveal><h2 id="work-heading">{d.slug==="orbit"?<>Objects of<br/><em>curiosity.</em></>:d.slug==="form"?<>WORK<br/><em>INDEX.</em></>:d.slug==="atelier"?<>The work<br/><em>journal.</em></>:d.slug==="prism"?<>MADE YOU<br/><em>LOOK.</em></>:d.slug==="terminal"?<>Project<br/><em>explorer_</em></>:<>Chapters in<br/><em>progress.</em></>}</h2><p>The question. My contribution.<br/>What the evidence can support.</p></div>
    <div className={s.filters}><div role="group" aria-label="Project categories">{categories.map(c=><button type="button" key={c} aria-pressed={filter===c} onClick={()=>{setFilter(c);setSelected(0);}}>{c}</button>)}</div><label><span className={s.srOnly}>Search projects</span><input aria-label="Search projects" type="search" value={query} onChange={e=>{setQuery(e.target.value);setSelected(0);}} placeholder={d.slug==="terminal"?"Find a project or tool_":"Search projects or tools"}/><span aria-hidden="true">⌕</span></label></div>
    <p className={s.count} aria-live="polite">{filtered.length} {filtered.length===1?"project":"projects"} in this view</p>
    {!active?<div className={s.empty}><h3>No matching work.</h3><button type="button" onClick={()=>{setQuery("");setFilter("All");}}>Reset filters <Arrow/></button></div>:
     d.slug==="form"?<div className={s.workList}>{filtered.map((p,i)=><details key={p.slug} open={i===selected} onToggle={e=>{if(e.currentTarget.open&&i!==selected)setSelected(i);}}><summary><span>{String(i+1).padStart(2,"0")}</span><h3>{p.title}</h3><span>{p.category}</span><span aria-hidden="true">+</span></summary><div className={s.indexDetail}><Art project={p}/><div><span className={s.micro}>{p.context}</span><p>{p.summary}</p><strong>{p.role}</strong>{action(p)}</div></div></details>)}</div>:
     d.slug==="prism"?<div className={s.carousel}><div className={s.carouselMain} key={active.slug}><Art project={active}/><div className={s.carouselCopy}><span className={s.micro}>{active.context}</span><h3>{active.title}</h3><p>{active.summary}</p><span>{active.role}</span>{action(active)}</div></div><div className={s.carouselControls}><button type="button" aria-label="Previous project" onClick={()=>select((selected-1+filtered.length)%filtered.length)}>←</button><div role="group" aria-label="Choose project">{filtered.map((p,i)=><button type="button" key={p.slug} aria-pressed={i===selected} aria-label={`Show ${p.title}`} onClick={()=>select(i)}>{String(i+1).padStart(2,"0")} <span>{p.title}</span></button>)}</div><button type="button" aria-label="Next project" onClick={()=>select((selected+1)%filtered.length)}>→</button></div></div>:
     d.slug==="terminal"?<div className={s.explorer}><div className={s.explorerList} role="group" aria-label="Choose project">{filtered.map((p,i)=><button type="button" key={p.slug} aria-pressed={i===selected} aria-label={`Show ${p.title}`} onClick={()=>select(i)}><span aria-hidden="true">{i===selected?"●":"○"}</span><strong>{p.title}</strong><small>{p.category}</small></button>)}</div><article className={s.explorerPanel} key={active.slug}><div className={s.explorerTop}><span>{active.slug}</span><span>PROJECT NOTES</span></div><Art project={active}/><div className={s.explorerCopy}><h3>{active.title}</h3><div className={s.explorerTabs} role="group" aria-label="Project information">{["contribution","question","limitations"].map(t=><button type="button" aria-pressed={tab===t} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className={s.explorerAnswer} key={tab} aria-live="polite"><span className={s.micro}>{tab==="contribution"?active.role:tab==="question"?active.sections[0]?.heading:"Scope & next steps"}</span><p>{tab==="contribution"?(active.sections.find(s=>/my contribution/i.test(s.heading))?.body??active.summary):tab==="question"?(active.sections[0]?.body??active.summary):active.sections.at(-1)?.body}</p></div><p className={s.tools}>{active.tools.join(" / ")}</p>{action(active)}</div></article></div>:
     <div className={d.slug==="orbit"?s.workDeck:d.slug==="atelier"?s.journal:s.chapterProjects}>{filtered.map((p,i)=><article key={p.slug} data-reveal>{d.slug==="atelier"?<button type="button" data-atelier-art className={s.workArtWrap} onClick={()=>open(p)} aria-label={`Read ${p.title} case study`}><AtelierSculpture kind={p.visual} paused={paused||reduced||!!opened}/><span className={s.workNumber} aria-hidden="true">{String(i+1).padStart(2,"0")}</span><span className={s.artOpen} aria-hidden="true">Read the story ↗</span></button>:<div className={s.workArtWrap}><Art project={p}/><span className={s.workNumber}>{String(i+1).padStart(2,"0")}</span></div>}<div className={s.workCopy}><span className={s.micro}>{p.context}</span><h3>{p.title}</h3><p>{p.summary}</p><span className={s.role}>{p.role}</span><p className={s.tools}>{p.tools.join(" / ")}</p>{action(p)}</div></article>)}</div>}
   </section>

   <section className={s.contact} id="contact" aria-labelledby="contact-heading"><div className={s.sectionLabel}><span>03 / The conversation</span><span>Something worth exploring?</span></div><div data-reveal>{d.slug==="atelier"&&<span className={s.contactSeal} aria-hidden="true">S.</span>}<h2 id="contact-heading">{d.slug==="form"?<>LET’S<br/><em>TALK.</em></>:d.slug==="prism"?<>SAY<br/><em>HELLO!</em></>:d.slug==="terminal"?<>Start a<br/><em>conversation_</em></>:<>The next<br/><em>connection.</em></>}</h2><p>Questions about my work, or a data opportunity in the UK.</p><div className={s.contactLinks}><a href={profile.links.linkedin}>LinkedIn <Arrow/></a><a href={profile.links.github}>GitHub <Arrow/></a></div></div></section>
  </main>
  {d.slug==="atelier"&&<AtelierNavigation/>}
  <footer className={s.footer}><span>Sudharsan Sankaran</span><a href="#work">Explore the work <Arrow/></a><a href="#home">Back to top ↑</a></footer>
  <button type="button" className={s.motionButton} aria-pressed={paused||reduced} disabled={reduced} onClick={()=>setPaused(!paused)}>{reduced?"Reduced motion":paused?"Resume motion":"Pause motion"}<span aria-hidden="true">{paused?"▷":"Ⅱ"}</span></button>

  <dialog ref={modal} className={s.dialog} onClose={()=>setOpened(null)} aria-labelledby="case-title"><div className={s.dialogBar}><span>Project case study</span><button type="button" onClick={()=>modal.current?.close()} aria-label="Close case study">×</button></div>{opened&&<>{d.slug==="atelier"&&<div className={s.caseCover}><AtelierSculpture kind={opened.visual} paused={paused||reduced}/></div>}<span className={s.micro}>{opened.context}</span><h2 id="case-title">{opened.title}</h2><p className={s.dialogLead}>{opened.summary}</p><div className={s.dialogRole}><span>My contribution</span><strong>{opened.role}</strong></div>{opened.sections.map(section=><section className={s.caseSection} key={section.heading}><h3>{section.heading}</h3><p>{section.body}</p></section>)}{opened.evidence==="elliptic-report"&&<section className={s.resultSection}><h3>Reported results, with context.</h3><ResultsExplorer/></section>}{opened.links.map(l=><a href={l.url} key={l.url}>{l.label} <Arrow/></a>)}</>}</dialog>
  <dialog ref={quick} className={`${s.dialog} ${s.quickDialog}`} aria-labelledby="quick-title"><div className={s.dialogBar}><span>A quick introduction</span><button type="button" onClick={()=>quick.current?.close()} aria-label="Close recruiter view">×</button></div><h2 id="quick-title">Sudharsan<br/>Sankaran.</h2><p className={s.dialogLead}>{profile.intro}</p><dl><div><dt>Direction</dt><dd>{profile.primaryDirection}<br/>Parallel interest: {profile.parallelDirection}</dd></div><div><dt>Education</dt><dd>{profile.education}<br/>{profile.institution}<br/>{profile.completion}</dd></div><div><dt>Experience</dt><dd>Supervisor, Sai Ram Industries, India<br/>August 2021–August 2025</dd></div><div><dt>Evidence</dt><dd>Group leader for the Bitcoin fraud detection project, with R modelling and feature importance; Python Q-learning coursework; Azure and Docker deployment support.</dd></div><div><dt>Developing next</dt><dd>SQL, Power BI and reproducible data workflows.</dd></div></dl><a className={s.dialogCta} href="#work" onClick={()=>quick.current?.close()}>Explore the work <Arrow/></a></dialog>
  <dialog ref={menu} className={`${s.dialog} ${s.menuDialog}`} aria-labelledby="menu-title"><div className={s.dialogBar}><span id="menu-title">Explore</span><button type="button" onClick={()=>menu.current?.close()} aria-label="Close navigation">×</button></div><nav aria-label="Expanded navigation">{["About","Work","Contact"].map(t=><a href={`#${t.toLowerCase()}`} key={t} onClick={()=>menu.current?.close()}>{t} <Arrow/></a>)}</nav><a href="#work" onClick={()=>menu.current?.close()}>Explore the work <Arrow/></a></dialog>
 </div>;
}
